config/routes.rb
SevenContact::Engine.routes.draw do
  resources :contact_records, except: [:edit]
end

app/models/seven_contact/concerns/contact_record.rb
module SevenContact::Concerns::ContactRecord
  extend ActiveSupport::Concern
  self.included do
    validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
    validates :content, presence: true
  end

end

app/models/seven_contact/contact_record.rb
module SevenContact
  class ContactRecord < ActiveRecord::Base
    include SevenContact::Concerns::ContactRecord
  end
end

app/controllers/seven_contact/application_controller.rb
module SevenContact
  class ApplicationController < ActionController::Base
  end
end

app/controllers/seven_contact/concerns/contact_records_controller.rb
module SevenContact::Concerns::ContactRecordsController
  extend ActiveSupport::Concern

  self.included do
    before_action :set_contact_record, only: [:show, :destroy]
  end

  def index
    @contact_records = SevenContact::ContactRecord.all
  end

  # GET /contact_records/1
  def show
  end

  # GET /contact_records/new
  def new
    @contact_record = SevenContact::ContactRecord.new
  end

  # POST /contact_records
  def create
    @contact_record = SevenContact::ContactRecord.new(contact_record_params)

    if @contact_record.save
      SevenContact::ContactMailer.send_mail(@contact_record).deliver_now
      redirect_to @contact_record, notice: 'Contact record was successfully created.'
    else
      render :new
    end
  end

  # DELETE /contact_records/1
  def destroy
    @contact_record.destroy
    redirect_to contact_records_url, notice: 'Contact record was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_contact_record
    @contact_record = SevenContact::ContactRecord.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def contact_record_params
    params[:contact_record].permit(:email, :name, :content)
  end
end

app/controllers/seven_contact/contact_records_controller.rb
require_dependency "seven_contact/application_controller"

module SevenContact
  class ContactRecordsController < ApplicationController
    include SevenContact::Concerns::ContactRecordsController
  end
end

app/helpers/seven_contact/application_helper.rb
module SevenContact
  module ApplicationHelper
  end
end

app/views/layouts/seven_contact/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SevenContact</title>
  <%= stylesheet_link_tag    "seven_contact/application", media: "all" %>
  <%= javascript_include_tag "seven_contact/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/seven_contact/contact_records/_form.html.erb
<%= form_for @contact_record, url: seven_contact.new_contact_record_path do |f| %>
  <% if @contact_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_record.errors.count, "error") %> prohibited this contact_record from being saved:</h2>

      <ul>
      <% @contact_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div>
      <%= f.label :content %>
      <%= f.text_area :content %>
    </div>
    <%= f.submit %>
  </div>
<% end %>

app/views/seven_contact/contact_records/edit.html.erb
<h1>Editing Contact Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_record %> |
<%= link_to 'Back', contact_records_path %>

app/views/seven_contact/contact_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contact Records</h1>

<table>
  <thead>
    <tr>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_records.each do |contact_record| %>
      <tr>
        <td><%= contact_record.email %></td>
        <td><%= link_to 'Show', seven_contact.contact_record_path(contact_record) %></td>
        <td><%= link_to 'Destroy', seven_contact.contact_record_path(contact_record), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact record', seven_contact.new_contact_record_path %>

app/views/seven_contact/contact_records/new.html.erb
<h1>New Contact Record</h1>

<%= render 'seven_contact/contact_records/form' %>

<%= link_to 'Back', seven_contact.contact_records_path %>

app/views/seven_contact/contact_records/show.html.erb
<p id="notice"><%= notice %></p>

<div>
  <p>Name:</p>
  <%= @contact_record.name %>
</div>
<div>
  <p>Email:</p>
  <%= @contact_record.email %>
</div>
<div>
  <p>Content:</p>
  <%= @contact_record.content %>
</div>

<%= link_to 'Back', seven_contact.contact_records_path %>